name: format-news
on: [push]
jobs:
  news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: rm -rf index.html happenings.html
      - run: python format_happenings.py
